[package]
name = "day-5"
version = "0.1.0"
edition = "2021"

[dependencies]
rstest.workspace = true
nom.workspace = true
nom-supreme.workspace = true
# Inherit dependencies from workspace
# <dependency>.workspace = true
