[package]
name = "day-8"
version = "0.1.0"
edition = "2021"

[dependencies]
rstest.workspace = true
nom.workspace = true
nom_locate.workspace = true
glam.workspace = true
# Inherit dependencies from workspace
# <dependency>.workspace = true
